### ISSUE TITLE
Understanding the MEME file

### ISSUE THREAD

**Issue by dd86k** [pt300/crot#1]
![image](https://cloud.githubusercontent.com/assets/8390674/9947559/f81b2c2c-5d68-11e5-8760-dc00d60528fc.png)
# tl;dr

(removed most of it because meh)

I have no idea about the structure of the file. So this is what I understand of it:

```
            Data type (0x00 || 0x01)
   Magic    |  Data (Single byte == 8x1 pixels)
|----+----| |  |
4D 45 4D 45 00 00 00 00 [...] (Loop)
                  |  |
                  |  More data
                  Another data type
```

**Comment by pt300** [comment]
1st 4 bytes must be equal to "meme". Then the next byte specifies type of image(explained in readme). Rest is image's data.

**Comment by pt300** [comment]
That's all. You just have to load that data

**Comment by dd86k** [comment]
```
4D 45 4D 45 00 00 00 00 ...
|--MEME---| |  |---DATA-...
            |
            Image type
```

Okay got it! Sorry, I'm really of a visual person.
(Visual C# hehuehuhe)
